### ISSUE TITLE
[US]: Accès Sans Connexion

### ISSUE THREAD

**Issue by VincentEnRoueLibre** [IUT-Blagnac/sae-3-01-devapp-g3a-5#92]
### User Story

En tant qu'administrateur, je veux être en mesure de me servir de l'application sans connexion à Internet afin de pouvoir l'utiliser sereinement dans différents salons

### Importance

Must (Default)

### Critères d'acceptation

- [x] Le projet fonctionne hors connexion

### Tâches associées

- [x] Écrire un test
- [x] Coder
- [x] Écrire la doc

**Comment by loispacqueteau** [comment]
Operationnels sauf pour les utilisations de la librairie "anime"  pour les confetti , et pdfmake
